---
- hosts: all
  name: ensure name-server + website are built on remote host
  remote_user: "{{ username }}"
  become: true

  roles:
    - role: paul.hugo

    - role: geerlingguy.certbot
      vars:
        certbot_create_if_missing: yes
        certbot_create_standalone_stop_services:
          - apache2
          - httpd
        certbot_admin_email: "{{ email }}"
        certbot_certs:
          - domains:
              - "{{ paul_leroux_srs }}"

    - role: geerlingguy.apache
      vars:
        apache_create_vhosts: true
        apache_vhosts_filename: "srs.conf"
        apache_vhosts:
          - servername: "{{ paul_leroux_srs }}"
            documentroot: "/var/www/html/adlin"
        apache_vhosts_ssl:
          - servername: "{{ paul_leroux_srs }}"
            documentroot: "/var/www/html/adlin"
            certificate_file: "{{ letsencrypt_srs }}/cert.pem"
            certificate_key_file: "{{ letsencrypt_srs }}/privkey.pem"
            certificate_chain_file: "{{ letsencrypt_srs }}/fullchain.pem"

        apache_mods_enabled:
          - rewrite
          - ssl
          - socache_shmcb
          - headers
      
    - role: paul.knot

    - role: paul.happydomain
