- name: ensure apache, certbot and knot are installed
  become: true
  ansible.builtin.apt:
    name:
      - knot
      - knot-dnsutils


- name: ensure knot configuration is copied
  become: true
  ansible.builtin.template:
    src: knot.conf.j2
    dest: /etc/knot/knot.conf
  notify:
    - restart knot

- name: check if knot zone conf already exists
  become: true
  stat:
    path: "/var/lib/knot/zones/{{ paul_leroux_srs }}.zone"
  register: knot_zone_exists
      
- name: ensure zones folder is created
  become: true
  file:
    path: /var/lib/knot/zones/
    state: directory
    group: knot
    owner: knot
  notify:
    - restart knot

- name: ensure knot zone config file is copied
  become: true
  ansible.builtin.template:
    src: template.zone.j2
    dest: "/var/lib/knot/zones/{{ paul_leroux_srs }}.zone"
  notify:
    - restart knot
  when: knot_zone_exists.stat.exists is defined and not knot_zone_exists.stat.exists

- name: enable knot service at start
  become: true
  ansible.builtin.service:
    name: knot
    enabled: true